# Generated by Django 4.2.11 on 2024-04-12 17:11

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='fecha creacion')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='fecha modificacion')),
                ('numero_cuenta', models.CharField(default=0, max_length=11, unique=True, verbose_name='Numero de cuenta')),
                ('saldo_cuenta', models.DecimalField(decimal_places=2, max_digits=30, verbose_name='Saldo Cuenta')),
                ('estado_cuenta', models.BooleanField(default=True, verbose_name='Estado de Cuenta')),
            ],
            options={
                'verbose_name': 'Cuenta Bancaria',
                'verbose_name_plural': 'Cuentas Bancarias',
                'db_table': 'cuenta_bancaria',
                'ordering': ['-fecha_creacion', '-fecha_modificacion'],
                'get_latest_by': 'fecha_creacion',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LogsTransacciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='fecha creacion')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='fecha modificacion')),
                ('descripcion_log', jsonfield.fields.JSONField()),
                ('referencia_cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.cuentabancaria', verbose_name='Referencia Cuenta Bancaria')),
            ],
            options={
                'verbose_name': 'Log Transacción',
                'verbose_name_plural': 'Logs Transacciones',
                'db_table': 'logs_trans_cuenta_bancaria',
                'ordering': ['-fecha_creacion', '-fecha_modificacion'],
                'get_latest_by': 'fecha_creacion',
                'abstract': False,
            },
        ),
    ]
